[[main]]
name = "文章"
url = "/posts/"
weight = 1

# [[main]]
# name = "文档"
# url = "/docs/"
# weight = 2

[[main]]
name = "Go语言设计与实现"
url = "/series/go源码"
weight = 3

[[main]]
name = "关于"
url = "/about/"
weight = 99
